import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import fc from 'fast-check';
import request from 'supertest';
import { app } from '../src/app.js';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SAMPLE_RULE_TRACE = JSON.stringify({
  evaluatedAt: '2024-03-15T10:00:00.000Z',
  inputs: { youngestTransactionAge: '10 hours', totalAmount: 0 },
  rules: [],
  recommendation: 'Standard Investigation',
  priority: 'Standard',
});

const VALID_ERROR_CODES = [
  'DISPUTE_NOT_FOUND',
  'INVALID_STATUS_TRANSITION',
  'MISSING_RESOLUTION_OUTCOME',
  'DISPUTE_IN_TERMINAL_STATE',
  'VALIDATION_ERROR',
  'INTERNAL_ERROR',
];

const ALL_STATUSES = [
  'Reported',
  'UnderInvestigation',
  'Escalated',
  'Resolved',
  'Referred',
] as const;
type Status = (typeof ALL_STATUSES)[number];

const VALID_TRANSITIONS = new Set<string>([
  'Reported->UnderInvestigation',
  'UnderInvestigation->Escalated',
  'UnderInvestigation->Resolved',
  'UnderInvestigation->Referred',
  'Escalated->Resolved',
]);

// Records to clean up after the suite.
let testCustomerId: number;
const createdDisputeIds: number[] = [];

function isIso8601(value: unknown): boolean {
  return typeof value === 'string' && !Number.isNaN(Date.parse(value));
}

async function makeDispute(status: Status): Promise<number> {
  const dispute = await prisma.dispute.create({
    data: {
      customerId: testCustomerId,
      status,
      category: 'Unauthorised/Fraudulent Charge',
      totalAmount: 5000,
      dateRaised: '2024-03-15T10:00:00.000Z',
      priority: 'Standard',
      recommendation: 'Standard Investigation',
      ruleTrace: SAMPLE_RULE_TRACE,
      resolutionOutcome: status === 'Resolved' ? 'Refunded' : null,
      transactions: {
        create: [
          {
            amount: 5000,
            merchant: 'Seed Merchant',
            timestamp: '2024-03-14T10:00:00.000Z',
            paymentType: 'Card',
          },
        ],
      },
    },
  });
  createdDisputeIds.push(dispute.id);
  return dispute.id;
}

// fast-check arbitraries -----------------------------------------------------

const arbPaymentType = fc.constantFrom('Card', 'ApplePay', 'EFT');

const arbValidTransaction = fc.record({
  amount: fc.integer({ min: 1, max: 50000 }),
  merchant: fc.string({ minLength: 1, maxLength: 12 }).filter((s) => s.trim().length > 0),
  timestamp: fc
    .integer({ min: new Date('2024-01-01').getTime(), max: new Date('2024-03-15').getTime() })
    .map((t) => new Date(t).toISOString()),
  paymentType: arbPaymentType,
});

describe('API Property Tests', () => {
  beforeAll(async () => {
    const customer = await prisma.customer.create({
      data: {
        name: 'Property Tester',
        contactReference: 'prop@email.co.za',
        accountIdentifier: 'ACC-PROP-ZA',
      },
    });
    testCustomerId = customer.id;
  });

  afterAll(async () => {
    // Delete by customerId so every dispute generated by fast-check is removed,
    // even ones whose ids were not captured in createdDisputeIds. Orphaned rows
    // would otherwise leak into the shared database and break seed.test.ts.
    const disputes = await prisma.dispute.findMany({
      where: { customerId: testCustomerId },
      select: { id: true },
    });
    const ids = disputes.map((d) => d.id);
    if (ids.length > 0) {
      await prisma.transaction.deleteMany({ where: { disputeId: { in: ids } } });
      await prisma.dispute.deleteMany({ where: { id: { in: ids } } });
    }
    await prisma.customer.deleteMany({ where: { id: testCustomerId } });
    await prisma.$disconnect();
  });

  // Property 1 -------------------------------------------------------------
  it('Property 1: totalAmount equals the sum of transaction amounts after create and add', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(arbValidTransaction, { minLength: 1, maxLength: 4 }),
        arbValidTransaction,
        async (transactions, extra) => {
          const createRes = await request(app)
            .post('/api/disputes')
            .send({ customerId: testCustomerId, transactions });
          expect(createRes.status).toBe(201);
          createdDisputeIds.push(createRes.body.id);

          const expectedTotal = transactions.reduce((sum, t) => sum + t.amount, 0);
          expect(createRes.body.totalAmount).toBeCloseTo(expectedTotal, 5);

          const addRes = await request(app)
            .post(`/api/disputes/${createRes.body.id}/transactions`)
            .send(extra);
          expect(addRes.status).toBe(200);
          expect(addRes.body.totalAmount).toBeCloseTo(expectedTotal + extra.amount, 5);
        }
      ),
      { numRuns: 15 }
    );
  });

  // Property 3 -------------------------------------------------------------
  it('Property 3: status transitions accepted iff the pair is in the valid set', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.constantFrom(...ALL_STATUSES),
        fc.constantFrom(...ALL_STATUSES),
        async (from, to) => {
          // Only set up disputes from non-terminal starting states.
          if (from === 'Resolved' || from === 'Referred') return;

          const id = await makeDispute(from);
          const body: { status: Status; resolutionOutcome?: string } = { status: to };
          if (to === 'Resolved') body.resolutionOutcome = 'Refunded';

          const res = await request(app).patch(`/api/disputes/${id}/status`).send(body);

          const isValid = VALID_TRANSITIONS.has(`${from}->${to}`);
          if (isValid) {
            expect(res.status).toBe(200);
            expect(res.body.status).toBe(to);
          } else {
            expect(res.status).toBe(400);
            expect(res.body.error.code).toBe('INVALID_STATUS_TRANSITION');
          }
        }
      ),
      { numRuns: 20 }
    );
  });

  // Property 4 -------------------------------------------------------------
  it('Property 4: terminal-state disputes reject status transitions and transaction additions', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.constantFrom<Status>('Resolved', 'Referred'),
        fc.constantFrom(...ALL_STATUSES),
        arbValidTransaction,
        async (terminal, target, txn) => {
          const id = await makeDispute(terminal);

          const statusRes = await request(app)
            .patch(`/api/disputes/${id}/status`)
            .send({
              status: target,
              ...(target === 'Resolved' ? { resolutionOutcome: 'Refunded' } : {}),
            });
          expect(statusRes.status).toBe(400);
          expect(['INVALID_STATUS_TRANSITION', 'DISPUTE_IN_TERMINAL_STATE']).toContain(
            statusRes.body.error.code
          );

          const txnRes = await request(app).post(`/api/disputes/${id}/transactions`).send(txn);
          expect(txnRes.status).toBe(400);
          expect(txnRes.body.error.code).toBe('DISPUTE_IN_TERMINAL_STATE');
        }
      ),
      { numRuns: 15 }
    );
  });

  // Property 5 -------------------------------------------------------------
  it('Property 5: all error responses conform to the envelope schema', async () => {
    const arbBadRequest = fc.oneof(
      // Non-existent dispute id.
      fc.record({ kind: fc.constant('get404'), id: fc.integer({ min: 900000, max: 999999 }) }),
      // Invalid create body.
      fc.record({ kind: fc.constant('badCreate') }),
      // Invalid transaction.
      fc.record({ kind: fc.constant('badTxn') })
    );

    await fc.assert(
      fc.asyncProperty(arbBadRequest, async (scenario) => {
        let res;
        if (scenario.kind === 'get404') {
          res = await request(app).get(`/api/disputes/${scenario.id}`);
        } else if (scenario.kind === 'badCreate') {
          res = await request(app).post('/api/disputes').send({ transactions: [] });
        } else {
          res = await request(app)
            .post('/api/disputes')
            .send({
              customerId: testCustomerId,
              transactions: [{ amount: -1, merchant: '', timestamp: 'x', paymentType: 'Z' }],
            });
        }

        expect(res.status).toBeGreaterThanOrEqual(400);
        const { error } = res.body;
        expect(error).toBeDefined();
        expect(VALID_ERROR_CODES).toContain(error.code);
        expect(typeof error.message).toBe('string');
        expect(error.message.length).toBeGreaterThan(0);
        expect(error.status).toBe(res.status);
        expect(isIso8601(error.timestamp)).toBe(true);
      }),
      { numRuns: 20 }
    );
  });

  // Property 6 -------------------------------------------------------------
  it('Property 6: invalid transactions are rejected with VALIDATION_ERROR on both endpoints', async () => {
    const arbInvalidTransaction = fc.oneof(
      arbValidTransaction.map((t) => ({ ...t, amount: 0 })),
      arbValidTransaction.map((t) => ({ ...t, amount: -1 * Math.abs(t.amount) - 1 })),
      arbValidTransaction.map((t) => ({ ...t, merchant: '' })),
      arbValidTransaction.map((t) => ({ ...t, timestamp: 'not-a-timestamp' })),
      arbValidTransaction.map((t) => ({ ...t, paymentType: 'Crypto' }))
    );

    // A non-terminal dispute used for the add-transaction endpoint.
    const liveDisputeId = await makeDispute('Reported');

    await fc.assert(
      fc.asyncProperty(arbInvalidTransaction, async (txn) => {
        const createRes = await request(app)
          .post('/api/disputes')
          .send({ customerId: testCustomerId, transactions: [txn] });
        expect(createRes.status).toBe(400);
        expect(createRes.body.error.code).toBe('VALIDATION_ERROR');

        const addRes = await request(app)
          .post(`/api/disputes/${liveDisputeId}/transactions`)
          .send(txn);
        expect(addRes.status).toBe(400);
        expect(addRes.body.error.code).toBe('VALIDATION_ERROR');
      }),
      { numRuns: 25 }
    );
  });

  // Property 7 -------------------------------------------------------------
  it('Property 7: filtered list results only contain matching status and priority', async () => {
    // Seed a spread of disputes across statuses and priorities.
    const priorities = ['P1', 'P2', 'Standard'];
    for (const status of ['Reported', 'UnderInvestigation', 'Escalated'] as Status[]) {
      for (const priority of priorities) {
        const dispute = await prisma.dispute.create({
          data: {
            customerId: testCustomerId,
            status,
            category: 'Unauthorised/Fraudulent Charge',
            totalAmount: 1000,
            dateRaised: '2024-03-15T10:00:00.000Z',
            priority,
            recommendation: 'Standard Investigation',
            ruleTrace: SAMPLE_RULE_TRACE,
          },
        });
        createdDisputeIds.push(dispute.id);
      }
    }

    await fc.assert(
      fc.asyncProperty(
        fc.subarray(['Reported', 'UnderInvestigation', 'Escalated', 'Resolved', 'Referred']),
        fc.subarray(['P1', 'P2', 'Standard']),
        async (statusFilter, priorityFilter) => {
          const params = new URLSearchParams();
          if (statusFilter.length > 0) params.set('status', statusFilter.join(','));
          if (priorityFilter.length > 0) params.set('priority', priorityFilter.join(','));

          const res = await request(app).get(`/api/disputes?${params.toString()}`);
          expect(res.status).toBe(200);

          for (const dispute of res.body) {
            if (statusFilter.length > 0) {
              expect(statusFilter).toContain(dispute.status);
            }
            if (priorityFilter.length > 0) {
              expect(priorityFilter).toContain(dispute.priority);
            }
          }
        }
      ),
      { numRuns: 20 }
    );
  });
});
